apiVersion: apps/v1
kind: Deployment
metadata:
  name: giraffe-app
spec:
  selector:
    matchLabels:
      app: giraffe-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: giraffe-app
    spec:
      containers:
      - name: giraffe-app
        image: giraffe
        imagePullPolicy: IfNotPresent
